config/routes.rb
Rails.application.routes.draw do
  get 'supported_choices/new'
  get 'supported_choices/create'
  get 'researchers/show'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      # root to: "user/dashboards#show"
    end
  end
  root to: 'pages#home'

  get 'dashboard', to: "user/dashboards#show"

  get '/test', to: 'coupons#index'

  # Abstract controller
  resources :supported_choices, only: [ :new, :create ]

  # Show coupons from a company
  resources :companies, only: :show

  # PENDING
  resources :used_coupons, only: [ :index ]

  resources :researchers, only: [ :show ]

  namespace :api, defaults: { format: :json } do
  namespace :v1 do
    resources :coupons, only: [ :index ]
    resources :companies, only: [ :index ]
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :researcher
  belongs_to :field
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :coupons
  validates :name, uniqueness: true, presence: true
  mount_uploader :logo, PhotoUploader
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :company
  validates :title, presence: true
  validates :company_id, presence: true
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :articles
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader

  before_create :set_slug

  scope :sorted_by_index, -> { order(index: :asc) }

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/models/researcher.rb
class Researcher < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :articles
  mount_uploader :photo, PhotoUploader
end

app/models/used_coupon.rb
class UsedCoupon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :field, optional: true
  belongs_to :researcher, optional: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from StandardError,                with: :internal_server_error
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private


  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < Api::V1::BaseController
  def index
    # get company from url
    @company = Company.where("url LIKE ?", "%" + params["company"] + "%")
    # get company_id from db
    @coupons = Coupon.where(company_id: @company[0].id)
    # call zanox api to get costumer track link
    # generate json with coupons and track link
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @company = Company.find(params[:id])
    @coupons = Coupon.where(company_id: @company.id)
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def index
    UpdateCouponsJob.perform_now
    @coupons = Coupon.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @researchers = Researcher.pluck(:full_name)
    @fields = Field.sorted_by_index
  end
end

app/controllers/researchers_controller.rb
class ResearchersController < ApplicationController
  def show
    @researcher = Researcher.find(params[:id])
    @articles = Article.where(researcher_id: @researcher.id)
  end
end

app/controllers/supported_choices_controller.rb
class SupportedChoicesController < ApplicationController
  def create
    if params[:field_id].present?
      current_user.researcher = nil
      current_user.field = Field.find(params[:field_id])
      current_user.save
      redirect_to "/dashboard"
    else
      current_user.field = nil
      current_user.researcher = Researcher.find(params[:researcher_id])
      current_user.save
      redirect_to "https://chrome.google.com/webstore/category/extensions"
    end
  end
end

app/controllers/used_coupons_controller.rb
class UsedCouponsController < ApplicationController
  def index
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  def show
    if current_user.field_id.present?
      @supported_choice = current_user.field
      @supported_name = @supported_choice.name
      @supported_description = @supported_choice.descritption
      @title = "Research Field Supported"
    else
      @supported_choice = current_user.researcher
      @supported_name = @supported_choice.full_name
      @supported_description = @supported_choice.bio
      @title = "Supported Researcher"
    end
    @companies = Company.all
    # redirect_to root_path if @field.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="verification" content="5ce5af6af297fcdb00686e421897a33f" />
    <title>$averZ - Help Fund Research While Shopping Online</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="home-container">
  <div class="row d-flex justify-content-center pt-5 pb-4">
    <h2>How does it work?</h2>
  </div>

  <div class="container">
    <div class="row how-works pt-3">
      <div class="col-md-3 px-3">
        <div class="card-how-works justify-content-center">
          <div class="round-icon d-flex justify-content-center">
            <span class="fa fa-2x fa-search d-flex justify-content-center"></span>
          </div>
          <h4 class="d-flex justify-content-center">Choose a Research</h4>
          <p class="d-flex justify-content-center">Choose a researcher or a field to support everytime you purchase.</p>
        </div>
      </div>

      <div class="col-md-3 px-3">
        <div class="card-how-works justify-content-center">
          <div class="round-icon d-flex justify-content-center">
            <span class="fa fa-2x fa-store d-flex justify-content-center"></span>
          </div>
          <h4 class="d-flex justify-content-center">Select a Store</h4>
          <p class="d-flex justify-content-center">Select the store you like and check all of their coupons.</p>
        </div>
      </div>

      <div class="col-md-3 px-3">
        <div class="card-how-works justify-content-center">
          <div class="round-icon d-flex justify-content-center">
            <span class="fa fa-2x fa-tags d-flex justify-content-center"></span>
          </div>
          <h4 class="d-flex justify-content-center">Save Money</h4>
          <p class="d-flex justify-content-center">Check all cupons avaiable that will help you and your researcher or field.</p>
        </div>
      </div>

      <div class="col-md-3 px-3">
        <div class="card-how-works justify-content-center">
          <div class="round-icon d-flex justify-content-center">
            <span class="fa fa-2x fa-donate d-flex justify-content-center"></span>
          </div>
          <h4 class="d-flex justify-content-center">Researcher Gains</h4>
          <p class="d-flex justify-content-center">A percentage of your purchase goes to the researcher or field.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<a id="target"><br></a>

<div class="text-center mt-5">
  <h2>Search Your Researcher Name ...</h2>
  <br>
</div>

<div class="search-banner">
  <div id="search-banner-home">
    <%= render 'shared/search' %>
  </div>
</div>

<div class="text-center mt-5">
  <h2>... Or Choose a UN Goal and Fund Research in That Area</h2>
</div>

<div class="container">
  <div class="row p-5">
    <% @fields.each do |field| %>
      <div class="col-md-3">
        <%= render "shared/popup_fields", field: field %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-container">
    <%= image_tag "saverz-vwhite.png" %>
    <h2>Get Discounts & Help Fund Research While Shopping</h2>
    <a class="arrow-link" href="#target">
      <div class="arrow-down mt-5 fas fa-5x fa-angle-double-down d-flex justify-content-center"></div>
    </a>
  </div>
</div>

<%# image_tag "saverz-vwhite.png", style:"width: 300px;" %>

app/views/shared/_companies_cards.html.erb
<div class="company-list">
  <% @companies.each do |company| %>
    <div class="each-company-card" >
      <div class="each-card-content">
      <%= link_to company.url, class: "company-image" do %>
        <img id="company-main-logo" src="<%= company.logo %>">
      <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_coupon_card.html.erb
<div class="coupon-card mb-4">
  <input type="text" id="<%= coupon.code %>-text" value="<%= coupon.code %>">
  <!-- <h2 id="<%= coupon.code %>-text"><%= coupon.code %></h2> -->
  <p><%= coupon.title %></p>
  <i  id="<%= coupon.code %>-copy" class="fas fa-copy copy-ico"></i>
  <%= link_to  coupon.tracking_url, target: :_blank do %><i class="fas fa-external-link-alt link-ico"></i><% end %>
</div>

<!-- JS plugin to copy-paste the coupon code -->
<script>
document.getElementById(`<%= coupon.code %>-copy`).addEventListener('click', function(e){
  document.getElementById(`<%= coupon.code %>-text`).select();
  var copied;
  copied = document.execCommand('copy');
  try
  {
    copied = document.execCommand('copy');
  } 
  catch (ex)
  {
    copied = false;  
  }

  if(copied)
  {
    // Display the copied text message
  }

});
</script>

app/views/shared/_footbar.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
   <div class="footer-copyright">
    - - - Be smart. Do good!
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer d-flex align-items">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <p>- - - Be smart. Do good!</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "saverz-v2.png", class: "nav_icon" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/daria0304", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div style="height: 50px;"></div>

app/views/shared/_navbarhome.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "saverz-v2.png", class: "nav_icon" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div style="height: 50px;"></div>

app/views/shared/_popup_fields.html.erb
<button type="button" class="btn" data-toggle="modal" data-target="#modal-<%= field.id %>">
  <%= cl_image_tag field.photo, class: "un-img-card" %>
</button>

<div class="modal fade" id="modal-<%= field.id  %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content field-card-modal">
      <div class="modal-body text-center">
        <div class="support-img-text d-flex">
          <div class="icon">
            <%= cl_image_tag field.photo, class: "card-img img-thumbnail", alt: field.photo %>
          </div>
          <div class="notice d-flex flex-column">
            <h4 class="pop-title"><%= field.name %></h4>
            <p class="pop-text"><%= field.descritption %></p>
          </div>
        </div>
        <div class="support-or-cancel justify-content-center  ">
          <%= button_to "#{supported_choices_path}?field_id=#{field.id}", method: :post, class:"btn-support" do %>
            Support
          <% end %>
          <%= link_to 'Choose another UN Goal', root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_popup_researcher.html.erb
<button type="button" class="btn" data-target="#modal" data-toggle="modal" %>
  Support
</button>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div>
          <div class="mx-5" style="font-family: 'Open Sans'; color: #292B3B">
            <br>
            <h3>Support the Researcher</h3>
            <br>

            <p>Download Chrome Extension to support your researcher and get coupons</p>
          </div>
        </div>

        <%= button_to supported_choices_path(researcher_id: @researcher), method: :post, target: :blank, class:"btn btn-danger" do %>
          <i class="fab fa-chrome"></i> &nbsp; Download Chrome Extension
        <% end %>
        <!-- <hr class="line"> -->
      </div>
      <br>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search position-relative">
  <% @researchers.each do |researcher_name| %>
    <% @researcher_page = Researcher.where(full_name: researcher_name).ids %>
  <% end %>
  <%= form_tag researcher_path(@researcher_page), method: :get do %>
    <%= text_field_tag :query,
                       params[:query],
                       class: "form-control",
                        autocomplete: 'off',
                       'data-filter': @researchers.to_json,
                       placeholder: "FIND YOUR RESEARCHER" %>
    <%= button_tag(type: "submit", class: "search-btn p-0 btn btn-light position-absolute") do %>
      <i class="fas fa-search"></i>
    <% end %>
    <div class="search-name-list hidden">
        <% @researchers.each do |researcher_name| %>
          <div data-name='<%= researcher_name %>' class="search-name-item hidden">
            <% photo = Researcher.where(full_name: researcher_name).first.photo %>
            <div class="reseacher-name d-flex">
              <%= link_to researcher_path(Researcher.where(full_name: researcher_name).ids) do %>
                <%= cl_image_tag photo %>
              <% end %>
              <%= link_to researcher_name, researcher_path(Researcher.where(full_name: researcher_name).ids) %>
            </div>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

<script>
  const query = document.querySelector('#query')
  query.addEventListener('keyup', (event) => {
    const filter = event.currentTarget.value;
    const searchNameItems = document.querySelectorAll('.search-name-item')
    const searchNameList = document.querySelector('.search-name-list')

    if (filter == '') {
      searchNameList.classList.add('hidden');
    } else {
      searchNameList.classList.remove('hidden');
      // carregar todos os elementos que comecam com filter
      searchNameItems.forEach((searchNameItem) => {
        // se o searchNameItem.data.name comecar com filter
        if (searchNameItem.dataset.name.toLowerCase().startsWith(filter.toLowerCase())) {
          searchNameItem.classList.remove('hidden');
        } else {
          searchNameItem.classList.add('hidden');
        }
      });
    }
  });

  const filteredResearchers = (researchers, filterString) => {
    return researchers.filter((researcher) => researcher.startsWith(filterString));
  }
</script>

app/views/shared/_search_more.html.erb
<div class="search-more-researcher">
  <%= form_tag new_supported_choice_path, method: :get do %>
    <%= text_field_tag :query, "", class: "form-control", placeholder: "FIND OTHER RESEARCHER TO SUPPORT" %>
    <%= button_tag(type: "submit", class: "search-btn pt-2 px-4 btn btn-light position-absolute") do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>